### ISSUE TITLE
Write a Program in python to find sum of two number's 

### ISSUE THREAD

**Issue by pranav2012** [pranav2012/Python-Hacktoberfest#1]

**Comment by rishavjaiss** [comment]
Hi, I'll do this!

**Comment by Bijoy-007** [comment]
> _No description provided._

i am here to do this

**Comment by pranav2012** [comment]
ok @Bijoy-007 I'm assigning this to you will merge after 1st October

**Comment by Bijoy-007** [comment]
I am very sorry I was excited so I already made a pull request

**Comment by pranav2012** [comment]
No, Problem don't be Happy coding will merge after 1st don't worry it will be counted :relaxed:
