### ISSUE TITLE
Write a Python Program to check if number is prime or not

### ISSUE THREAD

**Issue by pranav2012** [pranav2012/Python-Hacktoberfest#3]

**Comment by rishavjaiss** [comment]
Hi, I'll do this!

**Comment by HimadriPathak** [comment]
can i do this

**Comment by Bijoy-007** [comment]
Up for this one

**Comment by arnavk09** [comment]
Can I do this?

**Comment by pranav2012** [comment]
ok @arnavk09 I will assign you

**Comment by arnavk09** [comment]
> ok @arnavk09 I will assign you



where do I submit my code?

**Comment by pranav2012** [comment]
@arnavk09 fork the repository then in the python folder make a .py file nd write ur code then make a pull request.  For help in all these steps you can Google

**Comment by arnavk09** [comment]
> @arnavk09 fork the repository then in the python folder make a .py file nd write ur code then make a pull request. For help in all these steps you can Google



Got it, thanks!

**Comment by arnavk09** [comment]
> @arnavk09 fork the repository then in the python folder make a .py file nd write ur code then make a pull request. For help in all these steps you can Google



Hey I've generated the pull request, please verify the same

**Comment by pranav2012** [comment]
yes got it, @arnavk09 will start merging from 1st October onwards
