### ISSUE TITLE
Implement Stacks in Python

### ISSUE THREAD

**Issue by pranav2012** [pranav2012/Python-Hacktoberfest#8]

**Comment by HimadriPathak** [comment]
i will do this

**Comment by sejalshri** [comment]
I would like to work on this issue. Kindly assign it to me.

**Comment by pranav2012** [comment]
ok @sejalshri  I will assign you

**Comment by sejalshri** [comment]
hey please review it once https://github.com/sejalshri/Python-Hacktoberfest/commit/3beebd7d53ff5307c8670ec8f57bb5a28938cb27  .is it fine?
