### ISSUE TITLE
Write Quick Sort Algorithm in Python

### ISSUE THREAD

**Issue by pranav2012** [pranav2012/Python-Hacktoberfest#9]

**Comment by tusharsbauskar** [comment]
I would like to do this. Kindly assign me for this issue.

**Comment by pranav2012** [comment]
ok @tusharsbauskar

**Comment by Sahastracookcoder1** [comment]
Hi Pranav2012

Can I take this PR as I am comfortable with Data Structure and Algorithm in Python Language?
